// Everything that can move the global story forward.
//
// Screens never write the story position directly: they report *what the player
// did* and the transition table (story/transitions.js) decides whether that
// means anything from where the story currently stands. An event fired out of
// order is simply ignored, so a stray click can never skip a chapter.

export const STORY_EVENTS = Object.freeze({
  REUNION_COMPLETE: 'REUNION_COMPLETE',
  DEVICE_MIGRATION_COMPLETE: 'DEVICE_MIGRATION_COMPLETE',
  CHAT_RELOGIN_COMPLETE: 'CHAT_RELOGIN_COMPLETE',
  SEARCH_TUTORIAL_COMPLETE: 'SEARCH_TUTORIAL_COMPLETE',
  FIRST_SEARCH_PERFORMED: 'FIRST_SEARCH_PERFORMED',
  MIZUNO_FIRST_MESSAGE_RECEIVED: 'MIZUNO_FIRST_MESSAGE_RECEIVED',
  MIZUNO_THREAD_OPENED: 'MIZUNO_THREAD_OPENED',
  PROLOGUE_DM_COMPLETE: 'PROLOGUE_DM_COMPLETE',
  REVIVAL_LINK_RECEIVED: 'REVIVAL_LINK_RECEIVED',
  REVIVAL_OPENED: 'REVIVAL_OPENED',

  REVIVAL_EXPLORATION_COMPLETE: 'REVIVAL_EXPLORATION_COMPLETE',
  AFTER_REVIVAL_DM_COMPLETE: 'AFTER_REVIVAL_DM_COMPLETE',
  BBS_OPENED: 'BBS_OPENED',
  BASEMENT_MENTION_SEEN: 'BASEMENT_MENTION_SEEN',
  BBS_COMPLETE: 'BBS_COMPLETE',
  TWO_BIRDS_FOUND: 'TWO_BIRDS_FOUND',
  ACCESS_INFO_RESOLVED: 'ACCESS_INFO_RESOLVED',
  ORIGINAL_UNLOCKED: 'ORIGINAL_UNLOCKED',
  ORIGINAL_CLUES_READY: 'ORIGINAL_CLUES_READY',
  BASEMENT_PUZZLE_SOLVED: 'BASEMENT_PUZZLE_SOLVED',
  BASEMENT_ENTERED: 'BASEMENT_ENTERED',
  BASEMENT_INVESTIGATION_COMPLETE: 'BASEMENT_INVESTIGATION_COMPLETE',
  TIME_PATTERN_FOUND: 'TIME_PATTERN_FOUND',
  CLOCK_SEQUENCE_COMPLETE: 'CLOCK_SEQUENCE_COMPLETE',
  HYPOTHESIS_READY: 'HYPOTHESIS_READY',
  FINAL_RESOLVED: 'FINAL_RESOLVED',
  ENDING_COMPLETE: 'ENDING_COMPLETE'
})

export const STORY_EVENT_VALUES = Object.freeze(Object.values(STORY_EVENTS))

export function isKnownEvent(event){
  return STORY_EVENT_VALUES.includes(event)
}
